name: MacOS

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
        raku-version:
          - 'latest'

    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/checkout@v3

      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}

      - name: Raku version
        run: |
          raku -v.
          raku -V

      - name: Run Tests
        run: zef test --debug   .