name: Windows

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:

  build:
    strategy:
      matrix:
        os:
          - windows-latest
        raku-version:
          - 'latest'

    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/checkout@v3

      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}

      - name: Raku version
        run: |
          raku -v

      - name: Raku full version
        run: |
          raku -V

      - name: Run Tests
        run: zef test --debug .

  # Job below disabled
  build-bzip2-dll:

    # disable this job
    if: 0

    runs-on: windows-latest

    steps:

      # Windows runner doesn't have bzip2 installed, so get it from vcpkg

      # next two steps derived from https://learn.microsoft.com/en-gb/vcpkg/users/binarycaching#gha
      - uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Get bzip2 library from vcpkg
        run: vcpkg install bzip2:x64-windows --binarysource="clear;x-gha,readwrite"

      - name: Show installed bzip2 files created by vcpkg
        run: find /c/vcpkg/installed
        shell: bash

      # Next two steps make Artifacts avaiable for download
      - name: save bz2.dll
        run: |
          mkdir downloads
          cp /c/vcpkg/installed/x64-windows/bin/bz2.dll downloads
        shell: bash

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: assets
          path: downloads

  # Disabled variant that builds bzip2.dll from scratch
  # when using this change find-lib in Raw.pm6
  #
  build-all:

    # disable this job
    if: 0

    strategy:
      matrix:
        os:
          - windows-latest
        raku-version:
          - 'latest'

    env:
        LIBDIR: 'C:\vcpkg\installed\x64-windows\bin'

    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/checkout@v3

      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}

      - name: Raku version
        run: |
          raku -v

      - name: Raku full version
        run: |
          raku -V

      # Windows runner doesn't have bzip2 installed, so get it from vcpkg

      # next two steps derived from https://learn.microsoft.com/en-gb/vcpkg/users/binarycaching#gha
      - uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Get bzip2 library from vcpkg
        run: vcpkg install bzip2:x64-windows --binarysource="clear;x-gha,readwrite"

      - name: Show installed bzip2 files created by vcpkg
        run: find /c/vcpkg/installed
        shell: bash

      - name: append vclib installed lib dir to path
        run: |
          echo ${{ env.LIBDIR }} | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Show path
        run: |
          $Env:Path

      - name: Run Tests
        run: zef test --debug .